CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_type  VARCHAR(64)  NOT NULL,
    outcome     VARCHAR(16)  NOT NULL,
    actor_id    BIGINT,
    actor_email VARCHAR(120),
    target_type VARCHAR(64),
    target_id   VARCHAR(64),
    ip          VARCHAR(45),
    user_agent  VARCHAR(255),
    details     JSONB,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT now(),

    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_logs_actor      ON audit_logs (actor_id, created_at DESC);
CREATE INDEX idx_audit_logs_event      ON audit_logs (event_type, created_at DESC);

INSERT INTO permissions (name, description)
VALUES ('audit:read', 'Audit log''ni ko''rish')
    ON CONFLICT (name) WHERE deleted = FALSE DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'ADMIN' AND p.name = 'audit:read';