CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email        VARCHAR(120) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_date TIMESTAMP(6),
    updated_date TIMESTAMP(6),

    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_users_email_active ON users (email) WHERE deleted = FALSE;