CREATE TABLE permissions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(64) NOT NULL,
    description  VARCHAR(255),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_date TIMESTAMP(6),
    updated_date TIMESTAMP(6),

    CONSTRAINT pk_permissions        PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_permissions_name_active ON permissions (name) WHERE deleted = FALSE;

CREATE TABLE roles (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(64)  NOT NULL,
    description  VARCHAR(255),
    system_role  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_date TIMESTAMP(6),
    updated_date TIMESTAMP(6),

    CONSTRAINT pk_roles       PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_roles_name_active ON roles (name) WHERE deleted = FALSE;

CREATE TABLE role_permissions (
    role_id       BIGINT                         NOT NULL,
    permission_id BIGINT                         NOT NULL,

    CONSTRAINT    pk_role_permissions            PRIMARY KEY (role_id, permission_id),
    CONSTRAINT    fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT    fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);


CREATE TABLE user_roles (
    user_id    BIGINT             NOT NULL,
    role_id    BIGINT             NOT NULL,

    CONSTRAINT pk_user_roles      PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY(user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY(role_id) REFERENCES roles (id)
);

CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);