CREATE TABLE permissions (
    id BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_date TIMESTAMP(6),
    updated_date TIMESTAMP(6),

    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
)

CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);